//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; F:\gonzalo andreu\INTI\Gonzalo\Arduino\Programacion Sensor Dallas\arduino-qt-continuous\drivers.py
///  Source class: TemperatureSensor
///  Generation timestamp: 2019-06-14T14:52:01.613570
///  Class code hash: db38f0a9c31023182ad24ccb107051ce64912160
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_user_h
#define inodriver_user_h

void user_setup();
void user_loop();
float get_TEMP(); 


#endif // inodriver_user_h