//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; F:\gonzalo andreu\INTI\Gonzalo\Arduino\examples-master\examples-master\arduino-qt-toogle-led\run.py
///  Source class: LEDDriver
///  Generation timestamp: 2019-06-14T14:21:25.581686
///  Class code hash: 8647375a3d456c77a25af7a8712a5951c71a1594
///
/////////////////////////////////////////////////////////////



#include "inodriver_user.h"
#include <Arduino.h>

void user_setup() {
  pinMode(13, OUTPUT);
}

void user_loop() {
}
// COMMAND: LED, FEAT: led
int get_LED() {
  return 0;
}

int set_LED(int value) {
  if (value>0)
      digitalWrite(13, HIGH);
   else
      digitalWrite(13, LOW);
   return 0;
}
